jaxon_ajax:
    app:
      namespace:                      "\\Jaxon\\App"

    lib:
      core:
        language:                      "en"
        encoding:                      "UTF-8"
        request:
          uri:                         "/jaxon"
        prefix:
          class:                       ""
        debug:
          on:                          false
          verbose:                     false
        error:
          handle:                      false

      js:
          lib:
          app:
          extern:                      false
          minify:                      false
